;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2017/7/18 23:59:12

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1003	1003	; My Project: BloomFilter Class Reference class_bloom_filter.html
#define IDH_1053	1053	; My Project: Class Hierarchy hierarchy.html
#define IDH_1001	1001	; My Project: Class Index classes.html
#define IDH_1000	1000	; My Project: Class List annotated.html
#define IDH_1044	1044	; My Project: Class Members functions.html
#define IDH_1045	1045	; My Project: Class Members - Enumerations functions_enum.html
#define IDH_1046	1046	; My Project: Class Members - Enumerator functions_eval.html
#define IDH_1047	1047	; My Project: Class Members - Functions functions_func.html
#define IDH_1048	1048	; My Project: Class Members - Typedefs functions_type.html
#define IDH_1049	1049	; My Project: Class Members - Variables functions_vars.html
#define IDH_1005	1005	; My Project: Configurator Class Reference class_configurator.html
#define IDH_1007	1007	; My Project: DnsThread Class Reference class_dns_thread.html
#define IDH_1009	1009	; My Project: DnsUrl Class Reference class_dns_url.html
#define IDH_1043	1043	; My Project: File List files.html
#define IDH_1050	1050	; My Project: File Members globals.html
#define IDH_1051	1051	; My Project: File Members globals_func.html
#define IDH_1052	1052	; My Project: File Members globals_vars.html
#define IDH_1011	1011	; My Project: Hash Class Reference class_hash.html
#define IDH_1013	1013	; My Project: HttpHeader Class Reference class_http_header.html
#define IDH_1015	1015	; My Project: HttpResponse Class Reference class_http_response.html
#define IDH_1017	1017	; My Project: Log Class Reference class_log.html
#define IDH_1054	1054	; My Project: Main Page index.html
#define IDH_1002	1002	; My Project: Member List class_bloom_filter-members.html
#define IDH_1004	1004	; My Project: Member List class_configurator-members.html
#define IDH_1006	1006	; My Project: Member List class_dns_thread-members.html
#define IDH_1008	1008	; My Project: Member List class_dns_url-members.html
#define IDH_1010	1010	; My Project: Member List class_hash-members.html
#define IDH_1012	1012	; My Project: Member List class_http_header-members.html
#define IDH_1014	1014	; My Project: Member List class_http_response-members.html
#define IDH_1016	1016	; My Project: Member List class_log-members.html
#define IDH_1018	1018	; My Project: Member List class_multi_io-members.html
#define IDH_1020	1020	; My Project: Member List class_plugin-members.html
#define IDH_1022	1022	; My Project: Member List class_plugin_mngr-members.html
#define IDH_1024	1024	; My Project: Member List class_raw_url-members.html
#define IDH_1026	1026	; My Project: Member List class_recv_thread-members.html
#define IDH_1028	1028	; My Project: Member List class_send_thread-members.html
#define IDH_1030	1030	; My Project: Member List class_socket-members.html
#define IDH_1032	1032	; My Project: Member List class_str_kit-members.html
#define IDH_1034	1034	; My Project: Member List class_thread-members.html
#define IDH_1036	1036	; My Project: Member List class_url_filter-members.html
#define IDH_1038	1038	; My Project: Member List class_url_queues-members.html
#define IDH_1040	1040	; My Project: Member List class_web_crawler-members.html
#define IDH_1019	1019	; My Project: MultiIo Class Reference class_multi_io.html
#define IDH_1021	1021	; My Project: Plugin Class Reference class_plugin.html
#define IDH_1023	1023	; My Project: PluginMngr Class Reference class_plugin_mngr.html
#define IDH_1025	1025	; My Project: RawUrl Class Reference class_raw_url.html
#define IDH_1027	1027	; My Project: RecvThread Class Reference class_recv_thread.html
#define IDH_1029	1029	; My Project: SendThread Class Reference class_send_thread.html
#define IDH_1031	1031	; My Project: Socket Class Reference class_socket.html
#define IDH_1042	1042	; My Project: src Directory Reference dir_68267d1309a1af8e8297ef4c3efbcdba.html
#define IDH_1055	1055	; My Project: src/BloomFilter.cpp File Reference _bloom_filter_8cpp.html
#define IDH_1056	1056	; My Project: src/BloomFilter.h File Reference _bloom_filter_8h.html
#define IDH_1057	1057	; My Project: src/BloomFilter.h Source File _bloom_filter_8h_source.html
#define IDH_1058	1058	; My Project: src/Configurator.cpp File Reference _configurator_8cpp.html
#define IDH_1059	1059	; My Project: src/Configurator.h File Reference _configurator_8h.html
#define IDH_1060	1060	; My Project: src/Configurator.h Source File _configurator_8h_source.html
#define IDH_1061	1061	; My Project: src/DnsThread.cpp File Reference _dns_thread_8cpp.html
#define IDH_1062	1062	; My Project: src/DnsThread.h File Reference _dns_thread_8h.html
#define IDH_1063	1063	; My Project: src/DnsThread.h Source File _dns_thread_8h_source.html
#define IDH_1064	1064	; My Project: src/Hash.cpp File Reference _hash_8cpp.html
#define IDH_1065	1065	; My Project: src/Hash.h File Reference _hash_8h.html
#define IDH_1066	1066	; My Project: src/Hash.h Source File _hash_8h_source.html
#define IDH_1067	1067	; My Project: src/Http.h File Reference _http_8h.html
#define IDH_1068	1068	; My Project: src/Http.h Source File _http_8h_source.html
#define IDH_1069	1069	; My Project: src/Log.cpp File Reference _log_8cpp.html
#define IDH_1070	1070	; My Project: src/Log.h File Reference _log_8h.html
#define IDH_1071	1071	; My Project: src/Log.h Source File _log_8h_source.html
#define IDH_1072	1072	; My Project: src/Main.cpp File Reference _main_8cpp.html
#define IDH_1073	1073	; My Project: src/MultiIo.cpp File Reference _multi_io_8cpp.html
#define IDH_1074	1074	; My Project: src/MultiIo.h File Reference _multi_io_8h.html
#define IDH_1075	1075	; My Project: src/MultiIo.h Source File _multi_io_8h_source.html
#define IDH_1076	1076	; My Project: src/Plugin.h File Reference _plugin_8h.html
#define IDH_1077	1077	; My Project: src/Plugin.h Source File _plugin_8h_source.html
#define IDH_1078	1078	; My Project: src/PluginMngr.cpp File Reference _plugin_mngr_8cpp.html
#define IDH_1079	1079	; My Project: src/PluginMngr.h File Reference _plugin_mngr_8h.html
#define IDH_1080	1080	; My Project: src/PluginMngr.h Source File _plugin_mngr_8h_source.html
#define IDH_1081	1081	; My Project: src/Precompile.h File Reference _precompile_8h.html
#define IDH_1082	1082	; My Project: src/Precompile.h Source File _precompile_8h_source.html
#define IDH_1083	1083	; My Project: src/RecvThread.cpp File Reference _recv_thread_8cpp.html
#define IDH_1084	1084	; My Project: src/RecvThread.h File Reference _recv_thread_8h.html
#define IDH_1085	1085	; My Project: src/RecvThread.h Source File _recv_thread_8h_source.html
#define IDH_1086	1086	; My Project: src/SendThread.cpp File Reference _send_thread_8cpp.html
#define IDH_1087	1087	; My Project: src/SendThread.h File Reference _send_thread_8h.html
#define IDH_1088	1088	; My Project: src/SendThread.h Source File _send_thread_8h_source.html
#define IDH_1089	1089	; My Project: src/Socket.cpp File Reference _socket_8cpp.html
#define IDH_1090	1090	; My Project: src/Socket.h File Reference _socket_8h.html
#define IDH_1091	1091	; My Project: src/Socket.h Source File _socket_8h_source.html
#define IDH_1092	1092	; My Project: src/StrKit.cpp File Reference _str_kit_8cpp.html
#define IDH_1093	1093	; My Project: src/StrKit.h File Reference _str_kit_8h.html
#define IDH_1094	1094	; My Project: src/StrKit.h Source File _str_kit_8h_source.html
#define IDH_1095	1095	; My Project: src/Thread.cpp File Reference _thread_8cpp.html
#define IDH_1096	1096	; My Project: src/Thread.h File Reference _thread_8h.html
#define IDH_1097	1097	; My Project: src/Thread.h Source File _thread_8h_source.html
#define IDH_1098	1098	; My Project: src/Url.cpp File Reference _url_8cpp.html
#define IDH_1099	1099	; My Project: src/Url.h File Reference _url_8h.html
#define IDH_1100	1100	; My Project: src/Url.h Source File _url_8h_source.html
#define IDH_1101	1101	; My Project: src/UrlFilter.h File Reference _url_filter_8h.html
#define IDH_1102	1102	; My Project: src/UrlFilter.h Source File _url_filter_8h_source.html
#define IDH_1103	1103	; My Project: src/UrlQueues.cpp File Reference _url_queues_8cpp.html
#define IDH_1104	1104	; My Project: src/UrlQueues.h File Reference _url_queues_8h.html
#define IDH_1105	1105	; My Project: src/UrlQueues.h Source File _url_queues_8h_source.html
#define IDH_1106	1106	; My Project: src/WebCrawler.cpp File Reference _web_crawler_8cpp.html
#define IDH_1107	1107	; My Project: src/WebCrawler.h File Reference _web_crawler_8h.html
#define IDH_1108	1108	; My Project: src/WebCrawler.h Source File _web_crawler_8h_source.html
#define IDH_1033	1033	; My Project: StrKit Class Reference class_str_kit.html
#define IDH_1035	1035	; My Project: Thread Class Reference class_thread.html
#define IDH_1037	1037	; My Project: UrlFilter Class Reference class_url_filter.html
#define IDH_1039	1039	; My Project: UrlQueues Class Reference class_url_queues.html
#define IDH_1041	1041	; My Project: WebCrawler Class Reference class_web_crawler.html
